//
//  CommonParams + Alerts.swift
//  HarhoApp
//
//  Created by HARSHIT on 23/03/23.
//

import Foundation
import UIKit

var LAST_MSG = ""
struct AlertsMessage {
    static let login = "Login successfully"
    static let setProfile = "Details updated succesfully"
    static let someThingWentWorng = "SomeThing went wrong"
    static let updateIntro = "Status updated successfully"
    static let meApiParam = "User detail fetch successfully"
    static let allPropagators = "All propagator "
    static let propagatorSteps = "Propagator data fetch successfully"
    static let propagatorProduct = " PropagatorProduct Data fetch successfully"
    static let linksApi = "Link Data fetch successfully"
    static let subCategory = " SubCategory Data fetch successfully"
    static let articlesApi = " Article Data fetch successfully"
    static let videoApi = " Videos Data fetch successfully"
    static let blogsApi = " Blogs Data fetch successfully"
    static let getCreative = "Creative Data fetch successfully"
    static let subCategoryInfo = "Propagator info Data fetch successfully"
    static let sunSetSubmission = "Sunset photo uploaded successfully"
    static let uploadImage = "Image uploaded successfully"
    static let quizQuestions = "Questions fetch successfully"
    static let quizAnswers = "Answers fetch successfully"
    static let leaderBoard = "Scores fetch successfully"
    static let months = "Months fetch successfully"
    static let faq = "Faq data fetch successfully"
    static let allNotification = "All notification data fetch successfully"
    static let notifications = "Notifications fetch successfully"
    static let helpApi = "help data  fetch successfully"
    static let userScore = "User score fetch successfully"
    static let selectedMonth = "Selected month fetch successfully"
    static let propCategory = "Prop Category data fetch successfully"
    static let subCategoryInfoAll = "Prop subCategoryInfoAll data fetch successfully"
    static let propStepMonthThird = "Prop StepMonth third data fetch successfully"
    static let installProcess = "Install Process data fetch successfully"
    static let notificationOtherCheck = "Notification other check data fetch successfully"
    static let dailyCheckListProduct = "DailyCheckList Product data fetch successfully"
    static let notificationUpdateCheckList = "Notification Update CheckList data fetch successfully"
    static let changeProduceData = "Change produce data fetch successfully"
    static let deleteAccount = "Account deleted successfully"
    static let lastLogin = "lastLogin successfully"
    static let logout = "logout successfully"
    static let updateScore = "update Score successfully"
    static let invalidToken = "Invalid Token."
    static let checkUserName = "unique username"
    static let reinstallProcess = "ReInstall Process data fetch successfully"
    static let userCheckList = "User Check list updated successfully"
    static let dailyCheckList = "dailyCheckList updated"
}

struct ApiParams {
    
    static let email = "email"
    static let refrenceId = "refrence_id"
    static let error = "error"
    static let name = "name"
    static let displayName = "display_name"
    static let age = "age"
    static let projectName = "project_name"
    static let whoseGrowing = "whose_growing"
    static let gender = "gender"
    static let terms_and_policies = "terms_and_policies"
    static let key = "key"
    static let value = "value"
    static let is_updated = "is_updated"
    static let image = "image"
    static let deviceToken = "device_token"
    static let deviceType = "device_type"
    static let questionId = "question_id"
    static let answerId = "answer_id"
    static let statusType = "answer"
    static let propagator_id = "propagator_id"
    static let month = "month"
    static let is_notifications = "is_notifications"
    static let is_harvest = "is_harvest"
    static let is_watering = "is_watering"
    static let is_benefits = "is_benefits"
    static let datearr = "datearr"
    static let installPropagator_id = "propagator_id"
    static let soil_change_date = "soil_change_date"
    static let last_login = "last_login"
}

struct UserDefaultKey {
    static let authorizationToken = "authorizationToken"
    static let deviceToken = "deviceToken"
    static let UserID = "UserID"
    static let UserName = "UserName"
    static let LastLoginDate = "LastLoginDate"
    static let openPopup = "openPopup"
    static let water = "water"
    static let condensation = "condensation"
    static let boxRotate = "boxRotate"
    static let healthBenefits = "healthBenefits"
    static let socialUpload = "socialUpload"
    static let harvesting = "harvesting"
    static let mealComplement = "mealComplement"
    static let preservation = "preservation"
    static let forum = "forum"
    static let signInstall = "signInstall"
    static let id = "id"
    
}
